import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/Globals/Header";

export const gilroy = localFont({
  src: [
    { path: "../public/fonts/Gilroy-Thin.ttf", weight: "100", style: "normal" },
    { path: "../public/fonts/Gilroy-ThinItalic.ttf", weight: "100", style: "italic" },
    { path: "../public/fonts/Gilroy-UltraLight.ttf", weight: "200", style: "normal" },
    { path: "../public/fonts/Gilroy-UltraLightItalic.ttf", weight: "200", style: "italic" },
    { path: "../public/fonts/Gilroy-Light.ttf", weight: "300", style: "normal" },
    { path: "../public/fonts/Gilroy-LightItalic.ttf", weight: "300", style: "italic" },
    { path: "../public/fonts/Gilroy-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/Gilroy-RegularItalic.ttf", weight: "400", style: "italic" },
    { path: "../public/fonts/Gilroy-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/Gilroy-MediumItalic.ttf", weight: "500", style: "italic" },
    { path: "../public/fonts/Gilroy-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../public/fonts/Gilroy-SemiBoldItalic.ttf", weight: "600", style: "italic" },
    { path: "../public/fonts/Gilroy-Bold.ttf", weight: "700", style: "normal" },
    { path: "../public/fonts/Gilroy-BoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-gilroy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-background ${gilroy.variable} h-full`}>
      <body className="p-6 h-full">
        <Header/>
        {children}
      </body>
    </html>
  );
}
